config/routes.rb
Rails.application.routes.draw do
  root :to => 'stories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stories do
    resources :contributions do
      resources :comments, :only => [:new, :create]
    end
    resources :comments, :only => [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :content, :username
  belongs_to :commentable, polymorphic: true
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :story
  has_many :comments, :as => :commentable
  validates_presence_of :image_url, :username, :content


end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :contributions
  has_many :comments, :as => :commentable
  validates_presence_of :title, :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @story = Story.find(params[:story_id])
    if params[:contribution_id] == nil
      @comment = @story.comments.new
    else
      @contribution = Contribution.find(params[:contribution_id])
      @comment = @contribution.comments.new
    end
  end

  def create
    @story = Story.find(params[:story_id])
    if params[:contribution_id] == nil
      @comment = @story.comments.new(comment_params)
      if @comment.save
        redirect_to story_path(@story)
      else
        render :new
      end
    else
      @contribution = Contribution.find(params[:contribution_id])
      @comment = @contribution.comments.new(comment_params)
      if @comment.save
        redirect_to story_contribution_path(@story, @contribution, @comment)
      else
        render :new
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :username)
  end

end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

  def new
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.new
    @rss = Urss.at("http://www.flikr.com/services/feeds/photos_public.gne?format=rss_200"); true
    @rss_url = @rss.entries.first.medias.first.content_url
  end

  def create
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.new(contribution_params)
    if @contribution.save
      redirect_to story_path(@contribution.story)
    else
      render :new
    end
  end

  def show
    @story = Story.find(params[:story_id])
    @contribution = Contribution.find(params[:id])
  end

  def edit
    @story = Story.find(params[:story_id])
    @contribution = Contribution.find(params[:id])
    @rss_url = @contribution.image_url
  end

  def update
    @story = Story.find(params[:story_id])
    @contribution= Contribution.find(params[:id])
    if @contribution.update(contribution_params)
      redirect_to story_contribution_path(@story, @contribution)
    else
      render :edit
    end
  end

  def destroy
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
    redirect_to story_path(@contribution.story)
  end

  private
  def contribution_params
    params.require(:contribution).permit(:image_url, :username, :content)
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.order(title: :asc, created_at: :desc)
  end

  def show
    @story = Story.find(params[:id])
    @contributions = Story.find(params[:id]).contributions.order(created_at: :asc)
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      flash[:notice] = "Story successfully added!"
      redirect_to stories_path
    else
      render :new
    end
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story= Story.find(params[:id])
    if @story.update(story_params)
      flash[:notice] = "Edit Successful!"
      redirect_to stories_path
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

  private
  def story_params
    params.require(:story).permit(:title, :genre)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>

<%= form_for [@story, @contribution, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, :class => "form-control" %>
  </div>
  <%= f.submit, :class => "btn btn-success" %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

app/views/contributions/_form.html.erb
<%= render "layouts/errors", :object => @contribution %>

<%= form_for [@story, @contribution] do |f| %>
  <%= f.hidden_field :image_url, :value => @rss_url %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, :class => "form-control" %>
  </div>
  <%= f.submit "Contribute To Story", :class => "btn btn-success" %>
<% end %>

app/views/contributions/edit.html.erb
<h1>Edit this Business</h1>
<%= render 'form' %>

app/views/contributions/new.html.erb
<h1 class="text-center">New Contribution</h1>

<div class="row">
  <div class="col-sm-6">
    <%= image_tag(@rss_url, size: "400x400") %>
  </div>
  <div class="col-sm-6">
    <%= render 'form' %>
  </div>
</div>

app/views/contributions/show.html.erb
<h1><%= @contribution.username %></h1>
<p><%= image_tag(@contribution.image_url, size: "400x400") %></p>
<p><%= @contribution.content %></p>



<p><%= link_to "Edit", edit_story_contribution_path(@story, @contribution) %></p>
<p><%= link_to "Delete", story_contribution_path(@story, @contribution), :data => {:confirm => "You sure?", :method => "delete"} %></p>


<h4>Comments</h4>
<% @contribution.comments.each do |comment| %>
  <p><%= comment.content %></p>
  <p><%= comment.username %></p>
<% end %>
<p><%= link_to "Add Comment", new_story_contribution_comment_path(@story, @contribution) %></p>

<%= link_to "Return to #{@story.title}", story_path(@contribution.story) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Story Board", root_path, :class => "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stories/_form.html.erb
<%= render "layouts/errors", :object => @story %>

<div class="row">
  <div class="col-sm-8 well">
    <%= form_for @story do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :genre %>
        <%= f.text_field :genre, :class => "form-control" %>
      </div>
      <%= f.submit "Create Story", :class => "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>

<%= render "form" %>

app/views/stories/index.html.erb
<h1>Story list</h1>

<ul>
  <% @stories.each do |story| %>
    <li><%= link_to story.title, story_path(story)%></li>
  <%end%>
</ul>

<%= link_to "New Story", new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

app/views/stories/show.html.erb
<div class="row">
  <h1><%= @story.title %></h1>
  <div class="col-sm-8">
    <div>
      <% @contributions.each do |contrib| %>
        <span class="contribution-link">
          <%= contrib.content %>
          <div class="contribution-details">
            <%= image_tag contrib.image_url,size: "80x80" %>
            <%= contrib.username %>
            <%= link_to "View Comments", story_contribution_path(@story, contrib)%>
          </div>
        </span>
      <% end %>
    </div>

    <p>
      <%= link_to "Contribute to Story", new_story_contribution_path(@story), :class => "btn btn-primary" %>
      <%= link_to "Edit", edit_story_path(@story), :class => "btn btn-warning" %>
      <%= link_to "Delete", story_path(@story), :data => {:confirm => "You sure?", :method => "delete"}, :class => "btn btn-danger" %>
    </p>
  </div>

  <div class="col-sm-4">
    <h3>Comments</h3>
    <% @story.comments.each do |comment| %>
      <p><%= comment.content %></p>
      <p><%= comment.username %></p>
    <% end %>
    <p><%= link_to "Add Comment", new_story_comment_path(@story) %></p>
  </div>
</div>